version: "3"

services:
  client:
    build: ./front
    ports:
      - 8080:8080
    volumes:
      - ./front:/data
    environment:
      - API_URL=http://localhost:3000/

  server:
    build: ./back
    ports:
      - 3000:3000
    volumes:
      - ./back:/data
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
