version: 2.0
jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
            version: 18.09.3
      #- run:
      #    name : Getting docker
      #    command: curl https://get.docker.com | sh
     
      - deploy:
          name: Push application Docker image
          command: |

            env DOCKER_CLI_EXPERIMENTAL=enabled docker buildx ls
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name docker-multiarch && docker buildx inspect --builder docker-multiarch --bootstrap
            docker login  -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker buildx build -f front/Dockerfile_prod --platform linux/arm/v7,linux/amd64 --tag $DOCKER_HUB_USER_ID/front:latest --push .
            docker buildx build -f db/Dockerfile --platform linux/arm/v7,linux/amd64 --tag $DOCKER_HUB_USER_ID/mongodb:latest --push .
            docker buildx build -f back/Dockerfile_prod --platform linux/arm/v7,linux/amd64 --tag $DOCKER_HUB_USER_ID/front:latest --push .
