version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      #- run:
      #    name : Getting docker
      #    command: curl https://get.docker.com | sh
      - run:
          name: Enabling qemu
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Building arm based image.
          command: docker-compose  build
      - run:
          name: Listing built images
          command: docker images
      - deploy:
          name: Push application Docker image
          command: |
            docker login  -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag project_db $DOCKER_HUB_USER_ID/mongodb:latest
            docker tag project_server $DOCKER_HUB_USER_ID/back:latest
            docker tag project_front $DOCKER_HUB_USER_ID/front:latest
            docker push $DOCKER_HUB_USER_ID/back:latest
            docker push $DOCKER_HUB_USER_ID/front:latest
            docker push $DOCKER_HUB_USER_ID/db:latest