version: 2
jobs:
  build:
    machine: true
    image: jonoh/docker-buildx-qemu
    steps:
      - checkout
      #- run:
      #    name : Getting docker
      #    command: curl https://get.docker.com | sh
      - run:
          name: Listing built images
          command: docker images
    
      - deploy:
          name: Push application Docker image
          command: |

            docker login  -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker buildx build --file front/Dockerfile_prod --platform linux/arm/v7,linux/amd64 --tag $DOCKER_HUB_USER_ID/front:latest --push .
            docker buildx build --file db/Dockerfile --platform linux/arm/v7,linux/amd64 --tag $DOCKER_HUB_USER_ID/mongodb:latest --push .
            docker buildx build --file back/Dockerfile_prod --platform linux/arm/v7,linux/amd64 --tag $DOCKER_HUB_USER_ID/front:latest --push .