version: 2
jobs:
    
  build:
    machine: true
    steps:
      - checkout
      #- run:
      #    name : Getting docker
      #    command: curl https://get.docker.com | sh
      - run:
          name: Listing built images
          command: docker images
    
      - deploy:
          docker:
            - image: alemairebe/buildx
          name: Push application Docker image
          command: |

            docker login  -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker buildx build  --platform linux/arm/v7,linux/amd64 -f front/Dockerfile_prod --tag $DOCKER_HUB_USER_ID/front:latest --push .
            docker buildx build  --platform linux/arm/v7,linux/amd64 -f db/Dockerfile --tag $DOCKER_HUB_USER_ID/mongodb:latest --push .
            docker buildx build --platform linux/arm/v7,linux/amd64  -f back/Dockerfile_prod --tag $DOCKER_HUB_USER_ID/front:latest --push .