name: ci

on:
  push:
    tags:
      - 'v*'
    branches:
      - "bdd-migration"

jobs:
  multi:
    runs-on: ubuntu-latest
    env:
      VERSION: "1.0.8"
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'        
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.1.0 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dokerfile name. Optional, by default will be set to "Dockerfile".
          dockerfile_name: Dockerfile

          # Additional options of docker build command. (Optional)
          docker_options: "--no-cache"
          dockerfile_directory: "./back/"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: npm install in Front and Back
        run: cd ./front && npm install && cd .. 
      -
        name: Build and push FRONT ....
        uses: docker/build-push-action@v2
        with:
          context: ./front
          file: ./front/Dockerfile_prod
          platforms: linux/arm/v7
          push: true
          tags: |
            cypnose/front:latest
            cypnose/front:${{ env.VERSION }}
      
