name: ci

on:
  push:
    branches: master

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: npm install in Front and Back
        run: cd ./front && npm install && cd .. 
      -
        name: Build and push DB ....
        uses: docker/build-push-action@v2
        with:
          context: ./db
          file: ./db/Dockerfile_prod
          platforms: linux/arm/v7
          push: true
          tags: |
            cypnose/mongodb:latest
            cypnose/mongodb:1.0.1